version: '2'
services:
  runner:
    image: weahead/gitlab-ci-runner:latest
    build: .
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - runner-config:/etc/gitlab-runner
    environment:
      TOKEN: registration token
      URL: url of ci server
      EXECUTOR: runner executor
      NAME: runner name
      BASE_IMAGE: docker image
      ENV_VARS: environment variables injected into runner
volumes:
  runner-config:
    driver: local
